version: '3.3'

name: nest-development-dc
services:
  nest-db-development:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    expose:
      - '3306'
    volumes:
      - ./init_mysqldb:/docker-entrypoint-initdb.d
      - ./development/mysql_data:/var/lib/mysql
